# Docker Compose konfiqurasiyası
# 20 şəbəkə x 30 kompüter = 600 istifadəçi üçün

services:
  # PostgreSQL Database (opsional - gələcək üçün hazır)
  postgres:
    image: postgres:15
    container_name: test-postgres
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d test_database"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Shiny Test Application  
  shiny-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: test-shiny-app
    ports:
      - "3838:3838"
    environment:
      - SHINY_LOG_STDERR=1
      - APP_ENV=production
      - MAX_CONNECTIONS=600
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - test-network
    volumes:
      - shiny_logs:/var/log/shiny-server
    
  # Nginx Reverse Proxy (Load balancer üçün)
  nginx:
    image: nginx:alpine
    container_name: test-nginx
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - shiny-app
    restart: unless-stopped
    networks:
      - test-network

# Docker volumes
volumes:
  postgres_data:
    driver: local
  shiny_logs:
    driver: local

# Docker networks  
networks:
  test-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
